CREATE TABLE IF NOT EXISTS user_stats (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    exp BIGINT NOT NULL DEFAULT 0,
    fang BIGINT NOT NULL DEFAULT 0,
    bcoin BIGINT NOT NULL DEFAULT 0,
    level INT NOT NULL DEFAULT 1,
    total_playtime BIGINT NOT NULL DEFAULT 0,
    matches_played INT NOT NULL DEFAULT 0,
    total_spent BIGINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 1,
    last_online_at DATETIME NULL,
    last_join_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
